package com.prabhatech.videoanalytics.aievent.entity;

public enum AiEventType {
    FACE_DETECTION,
    FACE_RECOGNITION,
    HUMAN_DETECTION,
    VEHICLE_DETECTION,
    VEHICLE_RECOGNITION,
    ANPR,
    CROWD_DENSITY,
    INTRUSION_DETECTION,
    LINE_CROSSING,
    OBJECT_ABANDONMENT,
    OBJECT_REMOVED,
    MOTION_DETECTION,
    LOITERING_DETECTION,
    FIRE_DETECTION,
    SMOKE_DETECTION,
    PPE_DETECTION,
    HELMET_DETECTION,
    VEHICLE_COUNTING,
    PEOPLE_COUNTING,
    QUEUE_ANALYTICS,
    HEAT_MAP
}
